defaults: &defaults
  docker:
    - image: circleci/golang:1.10.2
  working_directory: /go/src/github.com/kobtea/iapetus

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run: |
          make setup
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/src/github.com/kobtea/iapetus
      - run: |
          make test
          make build
  tagging:
    <<: *defaults
    steps:
      - checkout
      - run: |
          make sync-tag
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/src/github.com/kobtea/iapetus
      - run: |
          sudo apt update
          sudo apt install -y rpm
          make release
          setup_remote_docker
          make docker-release
workflows:
  version: 2
  build_and_release:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  tagging:
    jobs:
      - tagging:
          filters:
            branches:
              only: master
