defaults: &defaults
  docker:
    - image: circleci/golang:1.10.2
  working_directory: /go/src/github.com/kobtea/iapetus

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run: |
          make setup
      - persist_to_workspace:
          root: .
          paths:
            - vendor
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: vendor
      - run: |
          make test
          make build
  tagging:
    <<: *defaults
    steps:
      - checkout
      - run: |
          make sync-tag
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: vendor
      - run: |
          make release
workflows:
  version: 2
  build_and_release:
    jobs:
      - setup
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - tagging:
          filters:
            branches:
              only: master
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
