defaults: &defaults
  docker:
    - image: circleci/golang:1.15
  working_directory: /go/src/github.com/kobtea/iapetus

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: |
          make test
          make build
  tagging:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - 31:e2:81:6f:be:ba:0e:6c:53:88:88:73:59:13:25:6d
      - checkout
      - run: |
          make sync-tag
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo apt update
          sudo apt install -y wget rpm
          make release
          make docker-release
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - release:
          requires:
            - build
          context: org-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  tagging:
    jobs:
      - tagging:
          filters:
            branches:
              only: master
