apiVersion: 1

deleteDatasources:
- name: Iapetus
  orgId: 1
- name: PrometheusPrimary
  orgId: 1
- name: PrometheusArchive
  orgId: 1

datasources:
- name: Iapetus
  type: prometheus
  access: direct
  orgId: 1
  url: http://localhost:19090
  isDefault: true
  version: 1
  editable: true
- name: PrometheusPrimary
  type: prometheus
  access: direct
  orgId: 1
  url: http://localhost:9090
  isDefault: false
  version: 1
  editable: true
- name: PrometheusArchive
  type: prometheus
  access: direct
  orgId: 1
  url: http://localhost:9091
  isDefault: false
  version: 1
  editable: true
