global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets:
    - 'localhost:9090'
  metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: ${1}_avg
- job_name: 'node'
  static_configs:
  - targets:
    - 'node1:9100'
    - 'node2:9100'
    - 'node3:9100'
  metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: ${1}_avg
