global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets:
    - 'localhost:9090'
- job_name: 'node'
  static_configs:
  - targets:
    - 'node1:9100'
    - 'node2:9100'
    - 'node3:9100'
